# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mizanscene' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mizanscene
  pod 'Alamofire'
  pod 'paper-onboarding'
  pod 'PinCodeTextField'
  pod 'SwiftyJSON'

  target 'MizansceneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MizansceneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
